# Generated by Django 4.2.10 on 2024-05-03 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_options_price_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='drone',
        ),
        migrations.AddField(
            model_name='drone',
            name='currency',
            field=models.CharField(default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='drone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
