# Generated by Django 4.2.10 on 2024-05-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_drone_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
