# Generated by Django 4.2.10 on 2024-05-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_drone_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='currency',
            field=models.CharField(default='TRY', max_length=4),
        ),
        migrations.AlterField(
            model_name='drone',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='drone',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
