# Generated by Django 4.2.10 on 2024-05-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_drone_currency_alter_drone_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='TRY', max_length=4),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
    ]
